version: '3.6'
services:
  dvsync-server:
    image: 'quay.io/actus-wirtenberger/dvsync-server'
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - ./out:/data

  dvsync-client:
    image: 'quay.io/actus-wirtenberger/dvsync-client'
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      DVSYNC_TOKEN: ${DVSYNC_TOKEN}

# vim:ts=2:sw=2:et
