version: '3.6'
services:
  dvsync-server:
    image: 'quay.io/suda/dvsync-server'
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    volumes:
      - ${PWD}/out:/data

  dvsync-client:
    image: 'quay.io/suda/dvsync-client'
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      DVSYNC_TOKEN: ${DVSYNC_TOKEN}
